symbol:
  pad: "$"
  punctuation: ";:,.!?¡¿—…\"()“” "
  letters: "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
  letters_ipa: "ɑɐɒæɓʙβɔɕçɗɖðʤəɘɚɛɜɝɞɟʄɡɠɢʛɦɧħɥʜɨɪʝɭɬɫɮʟɱɯɰŋɳɲɴøɵɸθœɶʘɹɺɾɻʀʁɽʂʃʈʧʉʊʋⱱʌɣɤʍχʎʏʑʐʒʔʡʕʢǀǁǂǃˈˌːˑʼʴʰʱʲʷˠˤ˞↓↑→↗↘'̩'ᵻ"

# Currently ignored. TODO: Replace hardcoded values
preprocess:
  sample_rate: 24000
  n_fft: 2048
  win_length: 1200
  hop_length: 300

# general configuration
model:
  multispeaker: false
  n_mels: 80
  style_dim: 128 # style vector size

text_aligner:
  hidden_dim: 256
  token_embedding_dim: 512

pitch_extractor:
  num_class: 1
  seq_len: 192
  leaky_relu_slope: 0.01

plbert:
  hidden_size: 768
  num_attention_heads: 12
  intermediate_size: 2048
  max_position_embeddings: 512
  num_hidden_layers: 12
  dropout: 0.1

# The decoder/vocoder converts mel spectograms + style to pcm
# config for decoder
decoder:
  type: 'vocos'
  hidden_dim: 512
  intermediate_dim: 1536
  num_layers: 8
  gen_istft_n_fft: 1200
  gen_istft_hop_size: 300

text_encoder:
  hidden_dim: 512
  kernel_size: 5
  n_layer: 3
  n_token: 178 # number of phoneme tokens

# The style encoder (and prosody encoder) generates
# a style embedding from audio
embedding_encoder:
  dim_in: 64
  hidden_dim: 512
  skip_downsamples: true

prosody_predictor:
  hidden_dim: 512
  n_layer: 3
  max_dur: 50 # maximum duration of a single phoneme
  dropout: 0.2

# speech language model config
slm:
  model: 'microsoft/wavlm-base-plus'
  sr: 16000 # sampling rate of SLM
  hidden: 768 # hidden size of SLM
  nlayers: 13 # number of layers of SLM
  initial_channel: 64 # initial channels of SLM discriminator head

# style diffusion model config
diffusion:
  embedding_mask_proba: 0.1
  # transformer config
  transformer:
    num_layers: 3
    num_heads: 8
    head_features: 64
    multiplier: 2

  # diffusion distribution config
  dist:
    sigma_data: 0.2 # placeholder for estimate_sigma_data set to false
    estimate_sigma_data: true # estimate sigma_data from the current batch if set to true
    mean: -3
    std: 1.0

slmadv_params:
  min_len: 400 # minimum length of samples
  max_len: 500 # maximum length of samples
  batch_percentage: 0.5 # to prevent out of memory, only use half of the original batch size
  iter: 10 # update the discriminator every this iterations of generator update
  thresh: 5 # gradient norm above which the gradient is scaled
  scale: 0.01 # gradient scaling factor for predictors from SLM discriminators
  sig: 1.5 # sigma for differentiable duration modeling
