training:
  out_dir: "your/output/dir"
  log_interval: 10
  save_interval: 2000
  val_interval: 2000
  device: "cuda"
  mixed_precision: "bf16" # "bf16", "fp16", or "no" for no mixed precision
  probe_batch_max: 35

training_plan:
  first: 10
  first_tma: 10
  second: 15
  second_style: 5
  second_joint: 10

dataset:
  train_data: "your/train_list.txt"
  val_data: "your/val_list.txt"
  wav_path: "your/wav/dir"
  OOD_data: "Data/OOD_texts.txt"
  min_length: 50 # sample until texts with this size are obtained for OOD texts

loss_weight:
  mel: 5 # mel reconstruction loss
  gen: 1 # generator loss
  slm: 1 # slm feature matching loss
  mono: 1 # monotonic alignment loss (1st stage, TMA)
  s2s: 1 # sequence-to-sequence loss (1st stage, TMA)
  # TODO: What should the weight of this be?
  magphase: 1
  F0: 1 # F0 reconstruction loss (2nd stage)
  norm: 1 # norm reconstruction loss (2nd stage)
  duration: 1 # duration loss (2nd stage)
  duration_ce: 20 # duration predictor probability output CE loss (2nd stage)
  style: 1 # style reconstruction loss (2nd stage)
  diffusion: 1 # score matching loss (2nd stage)

optimizer:
  lr: 0.0001 # general learning rate
  bert_lr: 0.00001 # learning rate for PLBERT
  ft_lr: 0.00001 # learning rate for acoustic modules
